mongodb:
  uri: "mongodb://localhost:27017"
  
  # Multi-database configuration (recommended)
  databases:
    - name: "aktuell"
      collections:
        - "users"

server:
  host: "localhost"
  port: 8080

logging:
  level: "info"